/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class online_zhaopei_myproject_common_tool_ExportTool */

#ifndef _Included_online_zhaopei_myproject_common_tool_ExportTool
#define _Included_online_zhaopei_myproject_common_tool_ExportTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     online_zhaopei_myproject_common_tool_ExportTool
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_online_zhaopei_myproject_common_tool_ExportTool_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     online_zhaopei_myproject_common_tool_ExportTool
 * Method:    generateExportFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_online_zhaopei_myproject_common_tool_ExportTool_generateExportFile
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
